apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: register-app
  template:
    metadata:
      labels:
        app: register-app
    spec:
      containers:
        - name: register-app
          image: mukeshjadav7696/register-app-pipeline:1.0.0-41
          resources:
            limits:
              memory: "200Mi"
              cpu: "350m"
          ports:
            - containerPort: 8080
